apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend
          ports:
            - containerPort: 3000
        env:
        - name: REACT_APP_MOVIE_API_URL
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_HOST
